# cargo make --makefile CargoMake.toml clippy
# cargo watch -x 'run'

[tasks.format]
# cargo +nightly fmt
command = "cargo"
args = ["+nightly", "fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.fix]
command = "cargo"
args = ["fix"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.cache]
command = "cargo"
args = ["cache"]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.my-flow]
dependencies = ["format", "build", "test"]
