version: '3.6'
services:
  tibetour-backend:
    build: .
    volumes:
      - tibetour-rust:/usr/src/myapp
    ports:
      - "9902:9902"
    restart: always
    environment:
      TZ: Asia/Shanghai

volumes:
  tibetour-rust:
