use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Serialize, Deserialize, DeriveEntityModel, DeriveActiveModelBehavior,
)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "finance_kingdee_cloud_voucher_combine")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    id: u32,
    operate_id: String,
    business_date: String,
    bookkeeping_date: String,
    company_finance_code: String,
    company_name: String,
    book_code: String,
    book_name: String,
    voucher_code: String,
    voucher_type: String,
    voucher_no: String,
    creator_code: String,
    creator_name: String,
    r#abstract: String,
    finance_account_code: String,
    finance_account_name: String,
    due_date: String,
    business_no: String,
    measure_unit_code: String,
    measure_unit_name: String,
    quantity: String,
    unit_price: String,
    currency_code: String,
    currency_name: String,
    debit_original_currency_amount: Decimal,
    credit_original_currency_amount: Decimal,
    currency_rate: f32,
    debit_amount: Decimal,
    credit_amount: Decimal,
    cashflow_code: String,
    cashflow_name: String,
    cashflow_supplement_name: String,
    cashflow_amount: Decimal,
    cashflow_supplement_code: String,
    cashflow_supplement_amount: Decimal,
    assist_account_name1: String,
    assist_account_item_code1: String,
    assist_account_item_name1: String,
    assist_account_name2: String,
    assist_account_item_code2: String,
    assist_account_item_name2: String,
    assist_account_name3: String,
    assist_account_item_code3: String,
    assist_account_item_name3: String,
    assist_account_name4: String,
    assist_account_item_code4: String,
    assist_account_item_name4: String,
    assist_account_name5: String,
    assist_account_item_code5: String,
    assist_account_item_name5: String,
    cashflow_assist_account_name1: String,
    cashflow_assist_account_item_code1: String,
    cashflow_assist_account_item_name1: String,
    cashflow_assist_account_name2: String,
    cashflow_assist_account_item_code2: String,
    cashflow_assist_account_item_name2: String,
    cashflow_assist_account_name3: String,
    cashflow_assist_account_item_code3: String,
    cashflow_assist_account_item_name3: String,
    cashflow_assist_account_name4: String,
    cashflow_assist_account_item_code4: String,
    cashflow_assist_account_item_name4: String,
    cashflow_assist_account_name5: String,
    cashflow_assist_account_item_code5: String,
    cashflow_assist_account_item_name5: String,
}

#[derive(Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
