use sea_orm::{DatabaseTransaction, DbErr, ExecResult};

pub async fn execute(txn: &DatabaseTransaction) -> Result<ExecResult, DbErr> {
    crate::execute_sql(txn,
        r#"
                CREATE TABLE ticket_bill (
                    id INT ( 11 ) NOT NULL AUTO_INCREMENT,
                    table_name VARCHAR ( 50 ) NOT NULL COMMENT '数据来源表名',
                    u8_table_name VARCHAR ( 50 ) COMMENT 'laiu8关联数据表名',
                    table_id BIGINT ( 20 ) NOT NULL COMMENT '数据来源表id',
                    u8_table_id INT ( 20 ) COMMENT 'laiu8关联数据id',
                    serial_no TINYINT ( 2 ) COMMENT '票变更序列号',
                    link_order_id BIGINT ( 20 ) COMMENT '关联票务订单号',
                    order_id BIGINT ( 20 ) COMMENT '票务订单号',
                    u8_order_key VARCHAR ( 20 ) COMMENT 'laiu8关联票务订单号=>统一字段类型 <u8_order_key=order_id>',
                    link_ticket_id VARCHAR ( 255 ) NOT NULL COMMENT '关联票务系统id <CONCAT_WS(",",ticket_id_old,ticket_id_new)>',
                    ticket_id_old BIGINT ( 20 ) COMMENT '关联旧票id',
                    u8_ticket_id_old VARCHAR ( 255 ) COMMENT 'laiu8关联旧票id=>统一字段类型',
                    ticket_id BIGINT ( 20 ) NOT NULL COMMENT '票务系统票id',
                    u8_ticket_num VARCHAR ( 255 ) COMMENT 'laiu8关联票务系统id=>统一字段类型 <u8_ticket_num=ticket_id>',
                    ticket_id_new BIGINT ( 20 ) COMMENT '关联新票id',
                    ticket_no BIGINT ( 20 ) COMMENT '票号',
                    u8_ticket_key VARCHAR ( 20 ) COMMENT 'laiu8关联票号 <IF(ticket_status=已换船,ticket_no_new,ticket_no)>',
                    ticket_no_new BIGINT ( 20 ) COMMENT '新订单的票号 退改升操作后新订单的票号',
                    channel_id BIGINT ( 20 ) COMMENT '渠道id',
                    u8_channel_id BIGINT ( 20 ) COMMENT 'laiu8渠道id',
                    channel_name VARCHAR ( 50 ) COMMENT '订票渠道',
                    u8_channel_name VARCHAR ( 50 ) COMMENT 'laiu8订票渠道',
                    user_id BIGINT ( 30 ) COMMENT '用户id <sys_user.code>',
                    u8_user_id BIGINT ( 30 ) COMMENT 'laiu8用户id',
                    user_type VARCHAR ( 50 ) COMMENT '客户类型 <bt_channel.category_id>',
                    u8_user_type VARCHAR ( 50 ) COMMENT 'laiu8用户类型',
                    user_name VARCHAR ( 50 ) COMMENT '用户名称',
                    u8_user_name VARCHAR ( 20 ) COMMENT 'laiu8用户名称',
                    u8_nickname VARCHAR ( 60 ) COMMENT 'laiu8用户昵称',
                    u8_vip_pact VARCHAR ( 50 ) COMMENT 'laiu8签约客户',
                    mobile VARCHAR ( 50 ) COMMENT '用户手机号',
                    ticket_type_name VARCHAR ( 50 ) COMMENT '票型',
                    product_type VARCHAR ( 50 ) COMMENT '产品类型',
                    change_order_id BIGINT ( 20 ) COMMENT '改签订单id <bt_ticket_change_order.id>',
                    change_type VARCHAR ( 50 ) COMMENT '<改签|升舱|补差|换船>操作',
                    ticket_status VARCHAR ( 50 ) COMMENT '船票状态',
                    flight_id BIGINT ( 20 ) COMMENT '航班id',
                    departure_datetime datetime COMMENT '航班时间',
                    line_code VARCHAR ( 50 ) COMMENT '航线code',
                    line_name VARCHAR ( 50 ) COMMENT '航线名称',
                    ship_name VARCHAR ( 50 ) COMMENT '船舶',
                    cabin_id BIGINT ( 20 ) COMMENT '舱位id',
                    cabin_name VARCHAR ( 50 ) COMMENT '舱位',
                    seat_memo VARCHAR ( 50 ) COMMENT '座位号',
                    passenger_name VARCHAR ( 50 ) COMMENT '乘船人',
                    passenger_id_no VARCHAR ( 50 ) COMMENT '证件号',
                    full_ticket_price DECIMAL ( 10, 3 ) COMMENT '原价',
                    discount_price DECIMAL ( 10, 3 ) COMMENT '折扣金额',
                    ticket_price DECIMAL ( 10, 3 ) COMMENT '票价',
                    get_voucher DECIMAL ( 10, 3 ) COMMENT '产生积分',
                    use_voucher DECIMAL ( 10, 3 ) COMMENT '使用积分',
                    pay_amount DECIMAL ( 10, 3 ) COMMENT '支付金额',
                    real_price DECIMAL ( 10, 3 ) COMMENT '实际金额',
                    payment_time datetime COMMENT '支付时间',
                    payment_method VARCHAR ( 50 ) COMMENT '支付方式',
                    u8_payment_method VARCHAR ( 50 ) COMMENT 'laiu8支付方式',
                    order_no VARCHAR ( 50 ) COMMENT '平台订单号 <laiu8.order_no>',
                    trade_no VARCHAR ( 40 ) COMMENT '商户订单号 <laiu8.trade_no>',
                    pay_id VARCHAR ( 50 ) COMMENT '支付号 <laiu8.callback_trade_no>',
                    refund_amount DECIMAL ( 10, 3 ) COMMENT '退票总额',
                    fee DECIMAL ( 10, 3 ) COMMENT '手续费',
                    is_lock TINYINT ( 1 ) DEFAULT '0' COMMENT '锁定状态<0=否,1=是>',
                    create_time datetime NOT NULL COMMENT '创建时间',
                    update_time datetime COMMENT '修改时间',
                    PRIMARY KEY ( id ),
                    KEY ix_table_id ( table_id ),
                    KEY ix_ticket_id ( ticket_id ),
                    KEY ix_link_order_id ( link_order_id ),
                    KEY ix_link_ticket_id ( link_ticket_id ),
                    KEY ix_ticket_id_new ( ticket_id_new ),
                    KEY ix_ticket_id_old ( ticket_id_old ),
                    KEY ix_order_id ( order_id ),
                    KEY ix_ticket_no ( ticket_no ),
                    KEY ix_u8_ticket_key ( u8_ticket_key ),
                    KEY ix_change_order_id ( change_order_id ),
                    KEY ix_flight_id ( flight_id ),
                    KEY ix_departure_datetime ( departure_datetime ),
                    KEY ix_trade_no ( trade_no ),
                    KEY ix_pay_id ( pay_id ),
                    KEY ix_payment_time ( payment_time ),
                    KEY ix_create_time ( create_time ),
                    KEY ix_u8_order_key ( u8_order_key ),
                    KEY ix_u8_ticket_num ( u8_ticket_num ),
                    KEY ix_u8_ticket_id_old ( u8_ticket_id_old )
                ) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;
            "#
    ).await
}
